In [1]:
import pycaret

print(pycaret.__version__)

3.3.2

In [49]:
import pandas as pd

# df = pd.read_csv("../data/Telco-Customer-Churn.csv")
df = pd.read_csv("../data/dados_saude_predicao.csv")

df.head()

,Idade,Pressao_Arterial,Colesterol_Total,Frequencia_Cardiaca_Max,Risco_Internacao
0,63,101,244,83,0
1,76,152,195,64,0
2,53,143,279,93,0
3,39,131,184,65,0
4,67,169,230,61,1

In [50]:
df.shape

(250, 5)

In [51]:
df.info

<bound method DataFrame.info of      Idade  Pressao_Arterial  Colesterol_Total  Frequencia_Cardiaca_Max  \
0       63               101               244                       83
1       76               152               195                       64
2       53               143               279                       93
3       39               131               184                       65
4       67               169               230                       61
..     ...               ...               ...                      ...
245     61               142               287                      101
246     56               143               294                       84
247     57               128               223                       77
248     25               112               166                       99
249     43               111               233                       67

     Risco_Internacao
0                   0
1                   0
2                   0
3                   0
4                   1
..                ...
245                 1
246                 1
247                 0
248                 0
249                 0

[250 rows x 5 columns]>

In [53]:
# df["Churn"].value_counts()
df["Risco_Internacao"].value_counts()

Risco_Internacao
0    125
1    125
Name: count, dtype: int64

In [54]:
df.isnull().sum

<bound method DataFrame.sum of      Idade  Pressao_Arterial  Colesterol_Total  Frequencia_Cardiaca_Max  \
0    False             False             False                    False
1    False             False             False                    False
2    False             False             False                    False
3    False             False             False                    False
4    False             False             False                    False
..     ...               ...               ...                      ...
245  False             False             False                    False
246  False             False             False                    False
247  False             False             False                    False
248  False             False             False                    False
249  False             False             False                    False

     Risco_Internacao
0               False
1               False
2               False
3               False
4               False
..                ...
245             False
246             False
247             False
248             False
249             False

[250 rows x 5 columns]>

In [12]:
df["TotalCharges"].dtype
df["TotalCharges"].value_counts().head()

TotalCharges
         11
20.2     11
19.75     9
20.05     8
19.9      8
Name: count, dtype: int64

In [55]:
from pycaret.classification import *

In [56]:
clf = setup(
    data=df,
    # target="Churn",
    target = "Risco_Internacao",
    session_id=123
)

In [57]:
best_model = compare_models()

In [64]:
knn = create_model(best_model)

In [65]:
evaluate_model(knn)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [66]:
tuned_knn = tune_model(knn)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [67]:
print(knn)
print(tuned_knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=-1, n_neighbors=12, p=2,
                     weights='distance')

In [68]:
predictions = predict_model(tuned_knn)

In [69]:
predictions.head(25)

,Idade,Pressao_Arterial,Colesterol_Total,Frequencia_Cardiaca_Max,Risco_Internacao,prediction_label,prediction_score
227,76,115,224,81,0,0,0.6180
84,34,107,285,104,1,0,0.5582
187,26,122,298,102,1,0,0.6222
99,77,116,168,84,0,0,0.9049
228,73,123,252,88,0,1,0.7747
189,69,111,155,92,1,0,0.9212
108,25,159,254,104,0,1,0.7465
140,59,156,223,90,0,1,0.8781
75,78,116,294,85,1,1,0.8257
95,40,103,168,98,0,0,1.0000
77,28,147,290,66,0,1,0.5288
139,61,106,161,89,0,0,0.9392
121,59,146,196,101,1,1,0.5462
138,48,159,293,70,0,1,0.8745
129,31,142,198,96,0,0,0.8482
222,78,118,196,71,0,0,0.7649
170,56,104,154,85,0,0,1.0000
206,76,156,183,68,1,0,0.6468
235,73,132,240,94,1,1,0.8240
11,35,123,254,82,1,0,0.6060
13,77,169,207,90,1,1,0.7939
166,56,159,159,104,1,0,0.5494
155,79,162,304,63,1,1,1.0000
217,75,109,203,109,1,0,0.8218
238,41,150,179,64,0,0,0.9433

In [73]:
novo_cliente = df.drop(columns=["Risco_Internacao"]).iloc[[227]]

In [74]:
predict_model(
    tuned_knn,
    data=novo_cliente
)

,Idade,Pressao_Arterial,Colesterol_Total,Frequencia_Cardiaca_Max,prediction_label,prediction_score
227,76,115,224,81,0,0.618

In [75]:
import os
os.makedirs("models",exist_ok=True)

In [78]:
# save_model(tuned_knn,"models/churn_model_v1")
save_model(tuned_knn,"models/Risco_Internacao_v1")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Idade', 'Pressao_Arterial',
                                              'Colesterol_Total',
                                              'Frequencia_Cardiaca_Max'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None, include=[],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                       metric='euclidean', metric_params=None,
                                       n_jobs=-1, n_neighbors=12, p=2,
                                       weights='distance'))],
          verbose=False),
 'models/Risco_Internacao_v1.pkl')

In [80]:
# modelo_carregado = load_model("models/churn_model_v1")
modelo_carregado = load_model("models/Risco_Internacao_v1")

Transformation Pipeline and Model Successfully Loaded

In [81]:
predict_model(
    modelo_carregado,
    data=novo_cliente
)

,Idade,Pressao_Arterial,Colesterol_Total,Frequencia_Cardiaca_Max,prediction_label,prediction_score
227,76,115,224,81,0,0.618